### ISSUE TITLE
Could this approach be used to enable building shared/static libs for Dart, the same way that .NET does?

### ISSUE THREAD

**Issue by GavinRay97** [fuzzybinary/dart-embedding-example#1]
Heya -- thank you for maintaining these examples!

As far as I can tell, you've never been able to build shared/static libs with Dart Native. Only binaries.

Looking at the embedding example and the embedding API here, I'm curious if the approach that .NET took with DNNE (Dotnet Native Exports) would be viable?

- https://github.com/AaronRobinsonMSFT/DNNE

The way this works is that you can mark functions with an attribute, to be exported (and the C99 code to generate for it if needed). At build time, it uses reflection to codegen a `.h` that:

1. Initializes the .NET VM
2. Loads in your program code
3. Sets function pointer definitions by reading them from the VM

And then it compiles this for you automatically.

```cs
private const string ReaperPluginInfoStructString = @"
  struct reaper_plugin_info_t
  {
    int caller_version;
    void* hwnd_main;
    int (*Register)(const char* name, void* infostruct);
    void* (*GetFunc)(const char* name);
  };
";

public struct ReaperPluginInfo {} // omitted

[UnmanagedCallersOnly]
[DNNE.C99DeclCode(ReaperPluginInfoStructString)]
public static int ReaperPluginEntry(IntPtr hInstance, [DNNE.C99Type("struct reaper_plugin_info_t*")] ReaperPluginInfo* rec)
```

```h
// Auto-generated by dnne-gen
// .NET Assembly: ReaperDNNE

// Declare exported functions
#ifndef __DNNE_GENERATED_HEADER_REAPERDNNE__
#define __DNNE_GENERATED_HEADER_REAPERDNNE__

#include <stddef.h>
#include <stdint.h>
#include <dnne.h>

// Additional code provided by user
      struct reaper_plugin_info_t
      {
        int caller_version;
        void* hwnd_main;
        int (*Register)(const char* name, void* infostruct);
        void* (*GetFunc)(const char* name);
      };
    

// Computed from ReaperDNNE.MyReaperPlugin.ReaperPluginEntry
DNNE_API int32_t DNNE_CALLTYPE ReaperPluginEntry(intptr_t hInstance, struct reaper_plugin_info_t* rec);

#endif // __DNNE_GENERATED_HEADER_REAPERDNNE__

// Define exported functions
#ifdef DNNE_COMPILE_AS_SOURCE

// Forward declarations
extern void* get_callable_managed_function(
    const char_t* dotnet_type,
    const char_t* dotnet_type_method,
    const char_t* dotnet_delegate_type);

extern void* get_fast_callable_managed_function(
    const char_t* dotnet_type,
    const char_t* dotnet_type_method);

// String constants
static const char_t* t1_name = DNNE_STR("ReaperDNNE.MyReaperPlugin, ReaperDNNE");

// Exports
// Computed from ReaperDNNE.MyReaperPlugin.ReaperPluginEntry
static int32_t (DNNE_CALLTYPE* ReaperPluginEntry_ptr)(intptr_t hInstance, struct reaper_plugin_info_t* rec);
DNNE_API int32_t DNNE_CALLTYPE ReaperPluginEntry(intptr_t hInstance, struct reaper_plugin_info_t* rec)
{
    if (ReaperPluginEntry_ptr == NULL)
    {
        const char_t* methodName = DNNE_STR("ReaperPluginEntry");
        ReaperPluginEntry_ptr = get_fast_callable_managed_function(t1_name, methodName);
    }
    return ReaperPluginEntry_ptr(hInstance, rec);
}

#endif // DNNE_COMPILE_AS_SOURCE
```

**Comment by fuzzybinary** [comment]
Hi @GavinRay97 (sorry for the late reply...)

I'm not sure what 100% sure what you're asking.

If you're just wondering if you could auto-generate C-callable functions that would initialize Dart for you and call into Dart code, I believe that's entirely possible, but probably outside of the scope of this example. This tells you how to initialize the Dart VM for embedding, and you could use that knowledge to create the generated code.

If you're more wondering about calling into compiled Dart, this example doesn't go into it, but you can initialize the Dart VM to compile .dart code, or load a pre-compiled library for JITting, or load an AOT compiled library. All three initialize about the same way with a few minor differences, but so far as I know you would still have to go through Dart functions to serialize / deserialize variables, so you can't just pull in a function pointer.

So, I *think* what you're asking is entirely possible, but probably won't be part of this repo.

Let me know if I totally misunderstood your question!

**Comment by GavinRay97** [comment]
Hey, no worries

> If you're just wondering if you could auto-generate C-callable functions that would initialize Dart for you and call into Dart code, I believe that's entirely possible, but probably outside of the scope of this example. This tells you how to initialize the Dart VM for embedding, and you could use that knowledge to create the generated code.


I _think_ this answers my question. Thank you!

Dart lets you compile Dart code to a binary. But you can't compile Dart code to a `.dll`/`.so`/`.dylib` etc.

Was curious if using this approach, you could produce a shared library, which exported your Dart methods as C-callable functions.

I think the only missing piece here for that is the codegen that you mentioned (which yes, is entirely out of scope for this).

**Comment by fuzzybinary** [comment]
Yes, that's accurate. You could codegen all the necessary stuff to create your own dynamically linked library. 

In reality, I'd love the dart team to support the embedded dart vm in a .dll / .so / .dylib, but I'm not sure that's coming any time soon.

**Comment by GavinRay97** [comment]
> In reality, I'd love the dart team to support the embedded dart vm in a .dll / .so / .dylib, but I'm not sure that's coming any time soon.

So would I. There's no reason it couldn't be done + by my estimate, one person could do the feature realistically over some sprints. (At least a minimal working implementation and codegen)

I brought this up in a GH issue where they outright ignored the question, and then I told them I felt hurt by being outright ignored (not even told "no we're not doing it") and then they told me it's an out-of-scope question for the issue.

🤷 

Priorities I guess
